# Generated by Django 6.0 on 2025-12-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=200)),
                ('brandDescription', models.CharField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='images/Products/')),
                ('productDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetailName', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('skin_type', models.CharField(max_length=1000, null=True)),
                ('main_benefit', models.CharField(max_length=1000, null=True)),
                ('availability', models.CharField(max_length=200, null=True)),
                ('productDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('brandID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.brand')),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetailImageName', models.CharField(max_length=200, null=True)),
                ('productDetailImage', models.ImageField(blank=True, null=True, upload_to='images/productDetail/')),
                ('imageDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aura.product')),
            ],
        ),
    ]
