# Generated by Django 6.0 on 2025-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0002_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(default='Luxé Beauty Team', max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Read time in minutes')),
                ('category', models.CharField(choices=[('routine', 'Skincare Routine'), ('ingredients', 'Ingredients'), ('seasonal', 'Seasonal Tips'), ('tips', 'Beauty Tips')], default='tips', max_length=20)),
                ('thumbnail', models.ImageField(help_text='Thumbnail for grid (recommended: 400x300 or 1:1)', upload_to='images/blog/thumbnails/')),
                ('featured_image', models.ImageField(blank=True, help_text='Large image for article page', null=True, upload_to='images/blog/featured/')),
                ('excerpt', models.TextField(help_text='Short teaser shown on homepage', max_length=500)),
                ('content', models.TextField(help_text='Full article content – you can use <p>, <h2>, <ul>, etc.')),
                ('slug', models.SlugField(help_text='e.g. double-cleansing-guide', max_length=200, unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from site')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
    ]
